# Site settings
title: 李涛的博客
admin: Taolee
SEOTitle: 李涛的博客 | Taolee's Blog
header-img: img/home-bg.jpg
email: litaotju@live.cn
description: ""
keyword: "Coder, Life is short, use python, Fun, Enjoy, Hungry, night"
url: "http://litaotju.github.io"              # your host, for absolute URL
baseurl: ""                               # for example, '/blog' if your blog hosted on 'host/blog'
#port: 10000
# SNS settings
RSS: false
#weibo_username:     TaoLee_TU
zhihu_username:     li-tao-64-13
github_username:    litaotju
#twitter_username:  huxpro
#facebook_username:  None

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","README.md", "README.zh.md", "venv", "Post.py"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
preview_post: true
# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]


# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important

# Disqus settings
disqus_username: taoleesblog

# Analytics settings
# Baidu Analytics
#ba_track_id: 4cc1f2d8f3067386cc5cdb626a202900
# Google Analytics
#ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
#ga_domain: litaoju.github.io



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "本人正在找工作中，欢迎联系"
sidebar-avatar: /img/avatar-taolee.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`
sidebar-contact-email: true
sidebar-resume: https://litaotju.gitbooks.io/resume/content/

# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value

# Friends
# friends: [
        # {
            # title: "李涛的简历",
            # href: "https://litaotju.gitbooks.io/resume/content/"
        # }
    # ,{
    #     title: "Foo",
    #     href: "#"
    # },{
    #     title: "Bar",
    #     href: "#"
    # },{
    #     title: "Example Friends",
    #     href: "#"
    # },{
    #     title: "It helps SEO",
    #     href: "#"
    # }
# ]
